apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  hostPath:
    path: /run/desktop/mnt/host/d/Resume 
  storageClassName: manual
